name: hello-world-workflow
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Custom Hello world Action
        uses: hellomadhur/my-helloworld-action@main

        
